/**
 * Abide Rule Guardrails System
 *
 * Enforces AGENTS.md and repository rules on every edit/diff using:
 * 1. RLCD deterministic checks (<1ms, local CPU, 0 tokens, AST/regex)
 * 2. Fast Jev System-2 Decision Classifier (~300ms, calibrated probability via the TypeSafe API)
 * 3. Adaptive Router with Graceful Fallback (Laya -> Jev -> Laya)
 */

import { JevClassifier } from "../classifiers/jev_classifier.js";
import type { DecisionClassifier } from "../classifiers/interface.js";
import type { TypedQuestion } from "../types.js";

export interface AbideRule {
  id: string;
  name: string;
  source: string; // e.g., "AGENTS.md line 145"
  instruction: string;
  when: "edit" | "turn";
  threshold: number; // 0.0 to 1.0 (default 0.70)
  // Deterministic checks executed by Laya in <1ms
  layaCheck?: {
    forbiddenFiles?: string[];
    forbiddenRegex?: RegExp[];
    requiredPatterns?: RegExp[];
  };
}

export interface RuleViolation {
  ruleId: string;
  ruleName: string;
  source: string;
  probability: number;
  message: string;
  repairInstruction: string;
  evaluator: "laya" | "jev";
}

export interface RuleEvaluationResult {
  allowed: boolean;
  violations: RuleViolation[];
  latencyMs: number;
  evaluatorUsed: "laya" | "jev" | "adaptive";
  /**
   * True when the semantic (Jev) pass was requested but could not run or could
   * not answer every rule — a missing key, a timeout, a network/API error, or
   * unusable answers. `allowed` then reflects the DETERMINISTIC checks only, so
   * a caller must report it as "not fully verified" instead of a clean pass.
   *
   * Guardrail semantics are unchanged: a Jev outage still never blocks the
   * agent. Only the reporting changes.
   */
  degraded?: boolean;
  /** Why the semantic pass was incomplete, when `degraded` is set. */
  degradationReason?: string;
  /** Semantic rules that were requested but produced no usable answer. */
  unevaluatedRuleIds?: string[];
}

/**
 * Standard default rules extracted and compiled from Aurapunk AGENTS.md
 */
export const AURAPUNK_STANDARD_RULES: AbideRule[] = [
  {
    id: "no-direct-shared-types",
    name: "Do not edit shared/types.ts directly",
    source: "AGENTS.md: Managing Shared Types",
    instruction:
      "Do not manually edit shared/types.ts, instead edit crates/server/src/bin/generate_types.rs and run pnpm run generate-types",
    when: "edit",
    threshold: 0.8,
    layaCheck: {
      forbiddenFiles: ["shared/types.ts", "*/shared/types.ts"],
    },
  },
  {
    id: "no-ai-attribution",
    name: "No AI attribution in commits or code",
    source: "AGENTS.md: Hard requirements",
    instruction:
      "No AI attribution lines (e.g. Co-Authored-By: Claude, Co-Authored-By: Assistant, Generated by AI) should be added to commits, trailers, or code files",
    when: "edit",
    threshold: 0.75,
    layaCheck: {
      forbiddenRegex: [
        /Co-Authored-By:\s*(Claude|OpenCode|Codex|Assistant|Gemini|GPT)/i,
        /Generated\s+with\s+(AI|Claude|Gemini|ChatGPT)/i,
        /🤖\s*Generated\s+by/i,
      ],
    },
  },
  {
    id: "no-manual-git-push-in-completion",
    name: "Do not manually push or merge in terminal completion",
    source: "AGENTS.md: Completion and Integration Guard Protocol",
    instruction:
      "Do not run git merge, git rebase, git update-ref, or git push manually for terminal completion; use complete_workspace_card tool instead",
    when: "edit",
    threshold: 0.85,
    layaCheck: {
      forbiddenRegex: [/\bgit\s+(push|rebase|merge|update-ref)\b/i],
    },
  },
  {
    id: "no-unprotected-secrets",
    name: "Never commit secrets or live API keys",
    source: "AGENTS.md: Security & Config Tips",
    instruction:
      "Never commit API keys, secrets, or private credentials directly in source files; use .env or safe env injection",
    when: "edit",
    threshold: 0.9,
    layaCheck: {
      forbiddenRegex: [
        /ts_live_[a-zA-Z0-9_-]{20,}/i,
        /sk-[a-zA-Z0-9]{32,}/i,
        /ghp_[a-zA-Z0-9]{36}/i,
      ],
    },
  },
];

export interface EvaluateDiffOptions {
  filePath: string;
  diff: string;
  rules?: AbideRule[];
  enabledRuleIds?: string[];
  engine?: "laya" | "jev" | "adaptive";
  jevApiKey?: string;
  jevBaseUrl?: string;
  classifierOverride?: DecisionClassifier;
}

/**
 * Evaluates a single file diff against repository rules.
 * Runs the RLCD deterministic checks first, with graceful escalation to Jev (TypeSafe) if needed.
 */
export async function evaluateDiffRules({
  filePath,
  diff,
  rules = AURAPUNK_STANDARD_RULES,
  enabledRuleIds,
  engine = "adaptive",
  jevApiKey,
  jevBaseUrl,
  classifierOverride,
}: EvaluateDiffOptions): Promise<RuleEvaluationResult> {
  const startTime = Date.now();
  const violations: RuleViolation[] = [];

  const activeRules = enabledRuleIds
    ? rules.filter((r) => enabledRuleIds.includes(r.id))
    : rules;

  // Extract added lines from diff
  const addedLines = diff
    .split("\n")
    .filter((line) => line.startsWith("+") && !line.startsWith("+++"))
    .map((line) => line.substring(1));
  const addedContent = addedLines.join("\n");

  // Step 1: RLCD deterministic checks
  for (const rule of activeRules) {
    if (rule.layaCheck) {
      // Check forbidden files
      if (rule.layaCheck.forbiddenFiles) {
        for (const pattern of rule.layaCheck.forbiddenFiles) {
          if (
            filePath === pattern ||
            filePath.endsWith(pattern.replace(/^\*\//, ""))
          ) {
            violations.push({
              ruleId: rule.id,
              ruleName: rule.name,
              source: rule.source,
              probability: 0.99,
              message: `Edit targets protected file: ${filePath}`,
              repairInstruction: `Abide: This edit appears to break a rule from this repository's instructions.\n- Rule "${rule.id}" from ${rule.source}: "${rule.instruction}". (0.99)\nRepair ${filePath} now, then continue with the task.`,
              evaluator: "laya",
            });
            break;
          }
        }
      }

      // Check forbidden regex in added lines
      if (rule.layaCheck.forbiddenRegex) {
        for (const regex of rule.layaCheck.forbiddenRegex) {
          if (regex.test(addedContent)) {
            violations.push({
              ruleId: rule.id,
              ruleName: rule.name,
              source: rule.source,
              probability: 0.95,
              message: `Added code matches forbidden pattern: ${regex.source}`,
              repairInstruction: `Abide: This edit appears to break a rule from this repository's instructions.\n- Rule "${rule.id}" from ${rule.source}: "${rule.instruction}". (0.95)\nRepair ${filePath} now, then continue with the task.`,
              evaluator: "laya",
            });
            break;
          }
        }
      }
    }
  }

  // If Laya found violations, return immediately (fast path <1ms)
  if (violations.length > 0 || engine === "laya") {
    return {
      allowed: violations.length === 0,
      violations,
      latencyMs: Date.now() - startTime,
      evaluatorUsed: "laya",
    };
  }

  // Step 2: System-2 Evaluation via Fast Jev (if enabled and rules require semantic check)
  const semanticRules = rules.filter(
    (r) => !violations.some((v) => v.ruleId === r.id),
  );

  if (semanticRules.length > 0 && (engine === "jev" || engine === "adaptive")) {
    let jevClassifier: DecisionClassifier | undefined = classifierOverride;

    if (!jevClassifier) {
      const hasTypeSafe = Boolean(jevApiKey);

      if (hasTypeSafe) {
        jevClassifier = new JevClassifier({
          apiKey: jevApiKey,
          baseUrl: jevBaseUrl,
          mode: "direct",
        });
      }
    }

    const semanticRuleIds = semanticRules.map((rule) => rule.id);

    // No client at all (no API key and no override): the semantic rules cannot
    // run. Deterministic checks passed, but that is not a clean semantic verdict.
    if (!jevClassifier) {
      return {
        allowed: violations.length === 0,
        violations,
        latencyMs: Date.now() - startTime,
        evaluatorUsed: "laya",
        degraded: true,
        degradationReason:
          "No Jev API key configured, so the semantic rules were not evaluated.",
        unevaluatedRuleIds: semanticRuleIds,
      };
    }

    try {
      const available = await jevClassifier.isAvailable();
      if (!available) {
        return {
          allowed: violations.length === 0,
          violations,
          latencyMs: Date.now() - startTime,
          evaluatorUsed: "laya",
          degraded: true,
          degradationReason:
            "Jev client reports unavailable (empty API key); semantic rules were not evaluated.",
          unevaluatedRuleIds: semanticRuleIds,
        };
      }

      const questions: Record<string, TypedQuestion> = {};
      for (const rule of semanticRules) {
        questions[`rule_${rule.id}`] = {
          type: "noul",
          instructions: `Does the following git diff violate this rule? Rule: "${rule.instruction}"`,
        };
      }

      const statePayload = `File: ${filePath}\nDiff:\n${diff}`;
      const evalResult = await jevClassifier.evaluateQuestions(
        statePayload,
        questions,
      );

      for (const rule of semanticRules) {
        const answer = evalResult.answers[`rule_${rule.id}`];
        if (answer && answer.type === "noul") {
          if (answer.probability >= rule.threshold) {
            violations.push({
              ruleId: rule.id,
              ruleName: rule.name,
              source: rule.source,
              probability: answer.probability,
              message: `Jev detected violation with probability ${answer.probability.toFixed(2)}`,
              repairInstruction: `Abide: This edit appears to break a rule from this repository's instructions.\n- Rule "${rule.id}" from ${rule.source}: "${rule.instruction}". (${answer.probability.toFixed(2)})\nRepair ${filePath} now, then continue with the task.`,
              evaluator: "jev",
            });
          }
        }
      }

      // A successful HTTP call with unusable or absent answers is not a pass:
      // report it as partially evaluated instead of a clean semantic verdict.
      const unevaluatedRuleIds = semanticRules
        .filter((rule) => !evalResult.answers[`rule_${rule.id}`])
        .map((rule) => rule.id);

      return {
        allowed: violations.length === 0,
        violations,
        latencyMs: Date.now() - startTime,
        evaluatorUsed: "jev",
        degraded: unevaluatedRuleIds.length > 0,
        degradationReason:
          unevaluatedRuleIds.length > 0
            ? `Jev returned no usable answer for ${unevaluatedRuleIds.length} of ${semanticRules.length} semantic rules.`
            : undefined,
        unevaluatedRuleIds:
          unevaluatedRuleIds.length > 0 ? unevaluatedRuleIds : undefined,
      };
    } catch (error) {
      // Never block the agent on a Jev outage — but never report a clean
      // semantic verdict either. `degraded` lets callers tell them apart.
      console.warn(
        `[Abide] Jev evaluation failed or timed out: ${(error as Error).message}. Falling back to the Laya deterministic verdict.`,
      );
      return {
        allowed: violations.length === 0,
        violations,
        latencyMs: Date.now() - startTime,
        evaluatorUsed: "laya",
        degraded: true,
        degradationReason: (error as Error).message,
        unevaluatedRuleIds: semanticRuleIds,
      };
    }
  }

  // Nothing semantic was requested (or everything was already decided above):
  // only the deterministic checks ran.
  return {
    allowed: violations.length === 0,
    violations,
    latencyMs: Date.now() - startTime,
    evaluatorUsed: "laya",
  };
}
