/**
 * Abide Rule Guardrails System
 *
 * Enforces AGENTS.md and repository rules on every edit/diff using:
 * 1. Laya System-1 Local Classifier (<1ms, local CPU, 0 tokens, deterministic AST/regex)
 * 2. Fast Jev System-2 Decision Classifier (~300ms, calibrated probability via TypeSafe or Vercel AI)
 * 3. Adaptive Router with Graceful Fallback (Laya -> Jev -> Laya)
 */

import { JevClassifier } from "../classifiers/jev_classifier.js";
import type { DecisionClassifier } from "../classifiers/interface.js";
import type { TypedQuestion } from "../types.js";

export interface AbideRule {
  id: string;
  name: string;
  source: string; // e.g., "AGENTS.md line 145"
  instruction: string;
  when: "edit" | "turn";
  threshold: number; // 0.0 to 1.0 (default 0.70)
  // Deterministic checks executed by Laya in <1ms
  layaCheck?: {
    forbiddenFiles?: string[];
    forbiddenRegex?: RegExp[];
    requiredPatterns?: RegExp[];
  };
}

export interface RuleViolation {
  ruleId: string;
  ruleName: string;
  source: string;
  probability: number;
  message: string;
  repairInstruction: string;
  evaluator: "laya" | "jev";
}

export interface RuleEvaluationResult {
  allowed: boolean;
  violations: RuleViolation[];
  latencyMs: number;
  evaluatorUsed: "laya" | "jev" | "adaptive";
}

/**
 * Standard default rules extracted and compiled from Aurapunk AGENTS.md
 */
export const AURAPUNK_STANDARD_RULES: AbideRule[] = [
  {
    id: "no-direct-shared-types",
    name: "Do not edit shared/types.ts directly",
    source: "AGENTS.md: Managing Shared Types",
    instruction:
      "Do not manually edit shared/types.ts, instead edit crates/server/src/bin/generate_types.rs and run pnpm run generate-types",
    when: "edit",
    threshold: 0.8,
    layaCheck: {
      forbiddenFiles: ["shared/types.ts", "*/shared/types.ts"],
    },
  },
  {
    id: "no-ai-attribution",
    name: "No AI attribution in commits or code",
    source: "AGENTS.md: Hard requirements",
    instruction:
      "No AI attribution lines (e.g. Co-Authored-By: Claude, Co-Authored-By: Assistant, Generated by AI) should be added to commits, trailers, or code files",
    when: "edit",
    threshold: 0.75,
    layaCheck: {
      forbiddenRegex: [
        /Co-Authored-By:\s*(Claude|OpenCode|Codex|Assistant|Gemini|GPT)/i,
        /Generated\s+with\s+(AI|Claude|Gemini|ChatGPT)/i,
        /🤖\s*Generated\s+by/i,
      ],
    },
  },
  {
    id: "no-manual-git-push-in-completion",
    name: "Do not manually push or merge in terminal completion",
    source: "AGENTS.md: Completion and Integration Guard Protocol",
    instruction:
      "Do not run git merge, git rebase, git update-ref, or git push manually for terminal completion; use complete_workspace_card tool instead",
    when: "edit",
    threshold: 0.85,
    layaCheck: {
      forbiddenRegex: [/\bgit\s+(push|rebase|merge|update-ref)\b/i],
    },
  },
  {
    id: "no-unprotected-secrets",
    name: "Never commit secrets or live API keys",
    source: "AGENTS.md: Security & Config Tips",
    instruction:
      "Never commit API keys, secrets, or private credentials directly in source files; use .env or safe env injection",
    when: "edit",
    threshold: 0.9,
    layaCheck: {
      forbiddenRegex: [
        /ts_live_[a-zA-Z0-9_-]{20,}/i,
        /sk-[a-zA-Z0-9]{32,}/i,
        /ghp_[a-zA-Z0-9]{36}/i,
      ],
    },
  },
];

export interface EvaluateDiffOptions {
  filePath: string;
  diff: string;
  rules?: AbideRule[];
  enabledRuleIds?: string[];
  engine?: "laya" | "jev" | "adaptive";
  jevApiKey?: string;
  vercelAiUrl?: string;
  vercelAiKey?: string;
  jevBaseUrl?: string;
  classifierOverride?: DecisionClassifier;
}

/**
 * Evaluates a single file diff against repository rules.
 * Runs Laya (System-1 <1ms CPU) first, with graceful escalation to Jev (System-2) if needed.
 */
export async function evaluateDiffRules({
  filePath,
  diff,
  rules = AURAPUNK_STANDARD_RULES,
  enabledRuleIds,
  engine = "adaptive",
  jevApiKey,
  vercelAiUrl,
  vercelAiKey,
  jevBaseUrl,
  classifierOverride,
}: EvaluateDiffOptions): Promise<RuleEvaluationResult> {
  const startTime = Date.now();
  const violations: RuleViolation[] = [];

  const activeRules = enabledRuleIds
    ? rules.filter((r) => enabledRuleIds.includes(r.id))
    : rules;

  // Extract added lines from diff
  const addedLines = diff
    .split("\n")
    .filter((line) => line.startsWith("+") && !line.startsWith("+++"))
    .map((line) => line.substring(1));
  const addedContent = addedLines.join("\n");

  // Step 1: Execute Laya System-1 Deterministic Checks
  for (const rule of activeRules) {
    if (rule.layaCheck) {
      // Check forbidden files
      if (rule.layaCheck.forbiddenFiles) {
        for (const pattern of rule.layaCheck.forbiddenFiles) {
          if (
            filePath === pattern ||
            filePath.endsWith(pattern.replace(/^\*\//, ""))
          ) {
            violations.push({
              ruleId: rule.id,
              ruleName: rule.name,
              source: rule.source,
              probability: 0.99,
              message: `Edit targets protected file: ${filePath}`,
              repairInstruction: `Abide: This edit appears to break a rule from this repository's instructions.\n- Rule "${rule.id}" from ${rule.source}: "${rule.instruction}". (0.99)\nRepair ${filePath} now, then continue with the task.`,
              evaluator: "laya",
            });
            break;
          }
        }
      }

      // Check forbidden regex in added lines
      if (rule.layaCheck.forbiddenRegex) {
        for (const regex of rule.layaCheck.forbiddenRegex) {
          if (regex.test(addedContent)) {
            violations.push({
              ruleId: rule.id,
              ruleName: rule.name,
              source: rule.source,
              probability: 0.95,
              message: `Added code matches forbidden pattern: ${regex.source}`,
              repairInstruction: `Abide: This edit appears to break a rule from this repository's instructions.\n- Rule "${rule.id}" from ${rule.source}: "${rule.instruction}". (0.95)\nRepair ${filePath} now, then continue with the task.`,
              evaluator: "laya",
            });
            break;
          }
        }
      }
    }
  }

  // If Laya found violations, return immediately (fast path <1ms)
  if (violations.length > 0 || engine === "laya") {
    return {
      allowed: violations.length === 0,
      violations,
      latencyMs: Date.now() - startTime,
      evaluatorUsed: "laya",
    };
  }

  // Step 2: System-2 Evaluation via Fast Jev (if enabled and rules require semantic check)
  const semanticRules = rules.filter(
    (r) => !violations.some((v) => v.ruleId === r.id),
  );

  if (semanticRules.length > 0 && (engine === "jev" || engine === "adaptive")) {
    let jevClassifier: DecisionClassifier | undefined = classifierOverride;

    if (!jevClassifier) {
      const hasVercel = Boolean(vercelAiKey || vercelAiUrl);
      const hasTypeSafe = Boolean(jevApiKey);

      if (hasVercel || hasTypeSafe) {
        jevClassifier = new JevClassifier({
          apiKey: jevApiKey,
          vercelAiKey,
          vercelAiUrl,
          baseUrl: jevBaseUrl,
          mode: hasVercel ? "vercel-ai" : "direct",
        });
      }
    }

    if (jevClassifier) {
      try {
        const available = await jevClassifier.isAvailable();
        if (available) {
          const questions: Record<string, TypedQuestion> = {};
          for (const rule of semanticRules) {
            questions[`rule_${rule.id}`] = {
              type: "noul",
              instructions: `Does the following git diff violate this rule? Rule: "${rule.instruction}"`,
            };
          }

          const statePayload = `File: ${filePath}\nDiff:\n${diff}`;
          const evalResult = await jevClassifier.evaluateQuestions(
            statePayload,
            questions,
          );

          for (const rule of semanticRules) {
            const answer = evalResult.answers[`rule_${rule.id}`];
            if (answer && answer.type === "noul") {
              if (answer.probability >= rule.threshold) {
                violations.push({
                  ruleId: rule.id,
                  ruleName: rule.name,
                  source: rule.source,
                  probability: answer.probability,
                  message: `Jev detected violation with probability ${answer.probability.toFixed(2)}`,
                  repairInstruction: `Abide: This edit appears to break a rule from this repository's instructions.\n- Rule "${rule.id}" from ${rule.source}: "${rule.instruction}". (${answer.probability.toFixed(2)})\nRepair ${filePath} now, then continue with the task.`,
                  evaluator: "jev",
                });
              }
            }
          }

          return {
            allowed: violations.length === 0,
            violations,
            latencyMs: Date.now() - startTime,
            evaluatorUsed: "jev",
          };
        }
      } catch (error) {
        // Fallback gracefully: if Jev times out or network fails, do not block the agent!
        console.warn(
          `[Abide] Jev evaluation failed or timed out: ${(error as Error).message}. Falling back to Laya safe verdict.`,
        );
      }
    }
  }

  return {
    allowed: violations.length === 0,
    violations,
    latencyMs: Date.now() - startTime,
    evaluatorUsed: engine === "jev" ? "jev" : "adaptive",
  };
}
